workspace:
  base: /go
  path: src/github.com/udistrital/citest/

pipeline:

build:

  # build and test the go program
  go:
    image: golang:1.9
    commands:
     - go get -t
     - GOOS=linux GOARCH=amd64 go build -o main
    when:
      branch: develop
      event: push


publish:

  # build and push docker image to docker hub
  docker:
    repo: oas0/citests
    tag:
      - $${COMMIT:0:7}
      - latest
    username: $$DRONE_DOCKERID_LOGIN
    password: $$DRONE_DOCKERID_PASSWORD
    email: computoud@googlegroups.com
    when:
      branch: develop
      event: push
